language: c
compiler:
  - gcc
  - clang
env:
  - EXTRA=libpcsclite-dev
script:
  - ./build-and-test.sh
before_install:
  - sudo apt-get update -qq
  - sudo apt-get remove -qq -y $REMOVE
  - sudo apt-get autoremove -qq
  - sudo apt-get install -qq -y gengetopt help2man $EXTRA
matrix:
  include:
    - compiler: gcc
      env: EXTRA="wine mingw-w64 mingw-w64-dev gnulib" REMOVE=mingw32 ARCH=32
    - compiler: gcc
      env: EXTRA="wine mingw-w64 mingw-w64-dev gnulib" REMOVE=mingw32 ARCH=64
